<?php

namespace ContainerG8LZ5W7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateTachesControllercreateTachesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vYYTk9.App\Controller\Api\Taches\CreateTachesController::createTaches()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vYYTk9.App\\Controller\\Api\\Taches\\CreateTachesController::createTaches()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'projetsRepository' => ['privates', 'App\\Repository\\Projets\\ProjetsRepository', 'getProjetsRepositoryService', true],
            'tachesRepository' => ['privates', 'App\\Repository\\Taches\\TachesRepository', 'getTachesRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'em' => '?',
            'projetsRepository' => 'App\\Repository\\Projets\\ProjetsRepository',
            'tachesRepository' => 'App\\Repository\\Taches\\TachesRepository',
            'validator' => '?',
        ]))->withContext('App\\Controller\\Api\\Taches\\CreateTachesController::createTaches()', $container);
    }
}
