<?php

namespace ContainerG8LZ5W7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteTachesControllerdeleteTacheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iT0Q6IK.App\Controller\Api\Taches\DeleteTachesController::deleteTache()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iT0Q6IK.App\\Controller\\Api\\Taches\\DeleteTachesController::deleteTache()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tachesRepository' => ['privates', 'App\\Repository\\Taches\\TachesRepository', 'getTachesRepositoryService', true],
        ], [
            'em' => '?',
            'tachesRepository' => 'App\\Repository\\Taches\\TachesRepository',
        ]))->withContext('App\\Controller\\Api\\Taches\\DeleteTachesController::deleteTache()', $container);
    }
}
