<?php

namespace ContainerG8LZ5W7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordResetControllerrequestResetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o6cYhft.App\Controller\Api\Users\PasswordReset\PasswordResetController::requestReset()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o6cYhft.App\\Controller\\Api\\Users\\PasswordReset\\PasswordResetController::requestReset()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepository' => ['privates', 'App\\Repository\\Users\\UsersRepository', 'getUsersRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'usersRepository' => 'App\\Repository\\Users\\UsersRepository',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\Api\\Users\\PasswordReset\\PasswordResetController::requestReset()', $container);
    }
}
