<?php

namespace Container1MFOORO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GjRRpgVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gjRRpgV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gjRRpgV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'accessRepository' => ['privates', 'App\\Repository\\Access\\AccessRepository', 'getAccessRepositoryService', true],
        ], [
            'accessRepository' => 'App\\Repository\\Access\\AccessRepository',
        ]);
    }
}
