<?php

namespace Container1MFOORO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetRolesControllergetAllRolesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JYjVmeV.App\Controller\Api\Roles\GetRolesController::getAllRoles()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JYjVmeV.App\\Controller\\Api\\Roles\\GetRolesController::getAllRoles()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rolesRepository' => ['privates', 'App\\Repository\\Roles\\RolesRepository', 'getRolesRepositoryService', true],
        ], [
            'rolesRepository' => 'App\\Repository\\Roles\\RolesRepository',
        ]))->withContext('App\\Controller\\Api\\Roles\\GetRolesController::getAllRoles()', $container);
    }
}
