<?php

namespace Container1MFOORO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUsersControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\Users\UpdateUsers\UpdateUsersController' shared autowired service.
     *
     * @return \App\Controller\Api\Users\UpdateUsers\UpdateUsersController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/Users/UpdateUsers/UpdateUsersController.php';

        $container->services['App\\Controller\\Api\\Users\\UpdateUsers\\UpdateUsersController'] = $instance = new \App\Controller\Api\Users\UpdateUsers\UpdateUsersController(($container->privates['App\\Service\\LogService'] ?? $container->load('getLogServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\Users\\UpdateUsers\\UpdateUsersController', $container));

        return $instance;
    }
}
