<?php

namespace Container1MFOORO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateProjetsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Projets\UpdateProjetsController' shared autowired service.
     *
     * @return \App\Controller\Projets\UpdateProjetsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Projets/UpdateProjetsController.php';

        $container->services['App\\Controller\\Projets\\UpdateProjetsController'] = $instance = new \App\Controller\Projets\UpdateProjetsController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Projets\\UpdateProjetsController', $container));

        return $instance;
    }
}
